import { getErrorMessage } from "@/utils";
import { postJsonRequest } from "./BaseRequests";

export const updateProduct = async ({
    idProduct,
    quantity,
    fabricCode,
    idSupplier,
    idCountry,
    cost,
    detail,
    idRise,
    idBodyFit,
    idLine,
    idConcept,
    idIndustry,
    idDepartment,
    year,
    idSeason,
    idMerchantBrand,
    idTipology,
    proyecta,
    sampleType,
    telas,
    avios,
    sizeCurveType,
    extendedSize,
    modelingDate,
    sampleDate,
    weight,
    idSampleStatus,
    idDesigner,
    idMerchant,
    idExistingProduct,
    name,
    idModeling,
    idCareLabel,
    measurmentTable,
    idModelingStatus,
    idStatusMeasurmentTable,
    idShoeMaterial,
    costInStore,
    pictures,
}) => {
    const path = `/dataSheet/updateProduct`;
    const body = {
        idProduct,
        quantity,
        fabricCode,
        idSupplier,
        idCountry,
        cost,
        detail,
        idRise,
        idBodyFit,
        idLine,
        idConcept,
        idIndustry,
        idDepartment,
        year,
        idSeason,
        idMerchantBrand,
        idTipology,
        proyecta,
        sampleType,
        telas,
        avios,
        sizeCurveType,
        extendedSize,
        modelingDate,
        sampleDate,
        weight,
        idSampleStatus,
        idDesigner,
        idMerchant,
        idExistingProduct,
        name,
        idModeling,
        idCareLabel,
        measurmentTable,
        idModelingStatus,
        idStatusMeasurmentTable,
        idShoeMaterial,
        costInStore,
        pictures,
    };

    try {
        const response = await postJsonRequest(path, body);
        return response;
    } catch (error) {
        throw new Error(getErrorMessage(error));
    }
};
