export const initialLayouts = {
    lg: [
        { w: 3, h: 7, x: 0, y: 0, i: "balance" },
        { w: 5, h: 7, x: 3, y: 0, i: "estadoDeProduccion" },
        { w: 4, h: 13, x: 8, y: 0, i: "embarques" },
        { w: 8, h: 6, x: 0, y: 7, i: "aprobacionesPendientes" },
        { w: 5, h: 6, x: 7, y: 7, i: "margen" },
        { w: 7, h: 18, x: 0, y: 7, i: "overall" },
        { w: 5, h: 12, x: 7, y: 12, i: "composicionPorColor" },
        /*
        const dashboard = {
    balance: <Balance />,
    estadoDeProduccion: <ProductionStatus />,
    embarques: <Shipments />,
    aprobacionesPendientes: <PendingApprovals />,
    margen: <Margin />,
    "": <Sections name="" />,
    composicionPorColor: <Sections name="all" layout="vertical" />,
};
        */
    ],
    md: [
        { w: 3, h: 7, x: 0, y: 0, i: "balance" },
        { w: 5, h: 7, x: 3, y: 0, i: "estadoDeProduccion" },
        { w: 4, h: 13, x: 8, y: 0, i: "embarques" },
        { w: 5, h: 6, x: 0, y: 7, i: "aprobacionesPendientes" },
        { w: 3, h: 6, x: 5, y: 7, i: "margen" },
        { w: 2, h: 8, x: 0, y: 13, i: "" },
        { w: 12, h: 12, x: 0, y: 21, i: "composicionPorColor" },
        // { w: 2, h: 6, x: 0, y: 7, i: "balance" },
        // { w: 5, h: 7, x: 0, y: 0, i: "estadoDeProduccion" },
        // { w: 5, h: 13, x: 5, y: 0, i: "embarques" },
        // { w: 4, h: 8, x: 0, y: 13, i: "aprobacionesPendientes" },
        // { w: 3, h: 6, x: 2, y: 7, i: "margen" },
        // { w: 2, h: 8, x: 4, y: 13, i: "camisetasTops" },
        // { w: 2, h: 8, x: 6, y: 13, i: "camisasBlusas" },
        // { w: 2, h: 8, x: 8, y: 13, i: "faldasShorts" },
        // { w: 2, h: 6, x: 0, y: 20, i: "vestidosMonos" },
        // { w: 2, h: 4, x: 0, y: 26, i: "muestrasEnviadas" },
        // { w: 8, h: 10, x: 2, y: 20, i: "skuYPiezasTotales" },
    ],
    sm: [
        { w: 3, h: 7, x: 0, y: 0, i: "balance" },
        { w: 5, h: 7, x: 3, y: 0, i: "estadoDeProduccion" },
        { w: 4, h: 13, x: 8, y: 0, i: "embarques" },
        { w: 5, h: 6, x: 0, y: 7, i: "aprobacionesPendientes" },
        { w: 3, h: 6, x: 5, y: 7, i: "margen" },
        { w: 2, h: 8, x: 0, y: 13, i: "" },
        { w: 12, h: 12, x: 0, y: 21, i: "composicionPorColor" },
        // { w: 1, h: 7, x: 0, y: 0, i: "balance" },
        // { w: 5, h: 7, x: 1, y: 0, i: "estadoDeProduccion" },
        // { w: 6, h: 8, x: 0, y: 7, i: "embarques" },
        // { w: 6, h: 6, x: 0, y: 15, i: "aprobacionesPendientes" },
        // { w: 2, h: 7, x: 0, y: 21, i: "margen" },
        // { w: 2, h: 7, x: 2, y: 21, i: "camisetasTops" },
        // { w: 2, h: 7, x: 4, y: 21, i: "camisasBlusas" },
        // { w: 2, h: 7, x: 0, y: 28, i: "faldasShorts" },
        // { w: 2, h: 7, x: 2, y: 28, i: "vestidosMonos" },
        // { w: 2, h: 7, x: 4, y: 28, i: "muestrasEnviadas" },
        // { w: 6, h: 8, x: 3, y: 35, i: "skuYPiezasTotales" },
    ],
    xs: [
        { w: 3, h: 7, x: 0, y: 0, i: "balance" },
        { w: 5, h: 7, x: 3, y: 0, i: "estadoDeProduccion" },
        { w: 4, h: 13, x: 8, y: 0, i: "embarques" },
        { w: 5, h: 6, x: 0, y: 7, i: "aprobacionesPendientes" },
        { w: 3, h: 6, x: 5, y: 7, i: "margen" },
        { w: 2, h: 8, x: 0, y: 13, i: "" },
        { w: 12, h: 12, x: 0, y: 21, i: "composicionPorColor" },
        // { w: 1, h: 7, x: 0, y: 21, i: "balance" },
        // { w: 4, h: 7, x: 1, y: 0, i: "estadoDeProduccion" },
        // { w: 4, h: 7, x: 0, y: 7, i: "embarques" },
        // { w: 4, h: 8, x: 0, y: 14, i: "aprobacionesPendientes" },
        // { w: 3, h: 8, x: 1, y: 21, i: "margen" },
        // { w: 2, h: 8, x: 0, y: 29, i: "camisetasTops" },
        // { w: 2, h: 8, x: 2, y: 29, i: "camisasBlusas" },
        // { w: 2, h: 8, x: 0, y: 37, i: "faldasShorts" },
        // { w: 4, h: 10, x: 2, y: 37, i: "vestidosMonos" },
        // { w: 4, h: 4, x: 0, y: 53, i: "muestrasEnviadas" },
        // { w: 4, h: 8, x: 0, y: 47, i: "skuYPiezasTotales" },
    ],
    xxs: [
        { w: 3, h: 7, x: 0, y: 0, i: "balance" },
        { w: 5, h: 7, x: 3, y: 0, i: "estadoDeProduccion" },
        { w: 4, h: 13, x: 8, y: 0, i: "embarques" },
        { w: 5, h: 6, x: 0, y: 7, i: "aprobacionesPendientes" },
        { w: 3, h: 6, x: 5, y: 7, i: "margen" },
        { w: 2, h: 8, x: 0, y: 13, i: "" },
        { w: 12, h: 12, x: 0, y: 21, i: "composicionPorColor" },
        // { w: 2, h: 7, x: 0, y: 0, i: "balance" },
        // { w: 2, h: 7, x: 3, y: 0, i: "estadoDeProduccion" },
        // { w: 2, h: 7, x: 8, y: 0, i: "embarques" },
        // { w: 2, h: 8, x: 0, y: 5, i: "aprobacionesPendientes" },
        // { w: 2, h: 8, x: 2, y: 5, i: "margen" },
        // { w: 2, h: 8, x: 4, y: 5, i: "camisetasTops" },
        // { w: 2, h: 8, x: 6, y: 5, i: "camisasBlusas" },
        // { w: 2, h: 10, x: 0, y: 12, i: "faldasShorts" },
        // { w: 2, h: 4, x: 10, y: 12, i: "muestrasEnviadas" },
        // { w: 2, h: 6, x: 10, y: 15, i: "skuYPiezasTotales" },
    ],
};
