export const initialLayouts = {
    lg: [
        { w: 3, h: 7, x: 0, y: 0, i: "balance" },
        { w: 5, h: 7, x: 3, y: 0, i: "estadoDeProduccion" },
        { w: 4, h: 13, x: 8, y: 0, i: "embarques" },
        { w: 8, h: 6, x: 0, y: 7, i: "aprobacionesPendientes" },
        { w: 7, h: 6, x: 0, y: 7, i: "margen" },
        { w: 5, h: 12, x: 7, y: 7, i: "resumenDeMaterialidades" },
        { w: 7, h: 18, x: 0, y: 13, i: "overall" },
        { w: 5, h: 12, x: 7, y: 19, i: "composicionPorColor" },
    ],
    md: [
        { w: 2, h: 7, x: 0, y: 0, i: "balance" },
        { w: 4, h: 7, x: 2, y: 0, i: "estadoDeProduccion" },
        { w: 4, h: 13, x: 8, y: 0, i: "embarques" },
        { w: 6, h: 6, x: 0, y: 7, i: "aprobacionesPendientes" },
        { w: 4, h: 6, x: 0, y: 7, i: "margen" },
        { w: 4, h: 12, x: 0, y: 13, i: "resumenDeMaterialidades" },
        { w: 6, h: 18, x: 5, y: 29, i: "overall" },
        { w: 6, h: 12, x: 5, y: 7, i: "composicionPorColor" },
    ],
    sm: [
        { w: 3, h: 7, x: 0, y: 0, i: "balance" },
        { w: 3, h: 7, x: 0, y: 0, i: "estadoDeProduccion" },
        { w: 3, h: 14, x: 3, y: 0, i: "embarques" },
        { w: 6, h: 6, x: 0, y: 7, i: "aprobacionesPendientes" },
        { w: 6, h: 5, x: 0, y: 7, i: "margen" },
        { w: 3, h: 9, x: 3, y: 18, i: "resumenDeMaterialidades" },
        { w: 6, h: 19, x: 0, y: 32, i: "overall" },
        { w: 3, h: 9, x: 0, y: 18, i: "composicionPorColor" },
    ],
    xs: [
        { w: 2, h: 7, x: 0, y: 0, i: "balance" },
        { w: 2, h: 7, x: 3, y: 0, i: "estadoDeProduccion" },
        { w: 4, h: 13, x: 8, y: 0, i: "embarques" },
        { w: 4, h: 6, x: 0, y: 7, i: "aprobacionesPendientes" },
        { w: 4, h: 6, x: 5, y: 7, i: "margen" },
        { w: 4, h: 9, x: 3, y: 13, i: "resumenDeMaterialidades" },
        { w: 4, h: 20, x: 0, y: 42, i: "overall" },
        { w: 4, h: 12, x: 0, y: 22, i: "composicionPorColor" },
    ],
    xxs: [
        { w: 2, h: 7, x: 0, y: 0, i: "balance" },
        { w: 2, h: 7, x: 3, y: 0, i: "estadoDeProduccion" },
        { w: 4, h: 13, x: 8, y: 0, i: "embarques" },
        { w: 4, h: 6, x: 0, y: 7, i: "aprobacionesPendientes" },
        { w: 4, h: 6, x: 5, y: 7, i: "margen" },
        { w: 4, h: 9, x: 3, y: 13, i: "resumenDeMaterialidades" },
        { w: 4, h: 20, x: 0, y: 42, i: "overall" },
        { w: 4, h: 12, x: 0, y: 22, i: "composicionPorColor" },
    ],
};
